config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :doses
  # resources :ingredient

  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_path, notice: 'cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    respond_to do |format|
      if @dose.save
        format.html { redirect_to @cocktail, notice: 'Dose was successfully created.' }
        format.json { render :show, status: :created, location: @dose }
      else
        format.html { render :new }
        format.json { render json: @dose.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    @cocktail = @dose.cocktail
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
  <div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 ">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class=navbar>
  <h1>Mister Cocktail</h1>
</div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1570598912132-0ba1dc952b7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60);">
  <div class="container">
    <h1>Cocktails</h1>
    <p>Your easy guide to getting drunk with style</p>
  </div>
</div>
<div class="container">
<div class="cards">
  <% @cocktails.each do |cocktail|  %>
    <% if cocktail.photo.attached? %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
        <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
        <p><%= link_to 'Delete', cocktail_path(cocktail.id), method: :delete, class:"btn btn-danger" %></p>
      </div>
    <% else %>
      <div class="card">
        <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
        <p><%= link_to 'Delete', cocktail_path(cocktail.id), method: :delete, class:"btn btn-danger" %></p>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to "Add a new cocktail", new_cocktail_path(@cocktail)%>
</div>

app/views/cocktails/new.html.erb
  <div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 ">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<ul>
  <% @doses.each do |dose| %>
  <li><%= dose.ingredient.name %>: <%= dose.description %></li>
  <%= link_to 'Delete', dose_path(dose), method: :delete, class:"btn btn-outline-danger btn-sm" %>
<% end %>
</ul>
<%= link_to "Add a New Dose", new_cocktail_dose_path(@cocktail), class:"btn btn-success" %>


<hr>
<%= link_to 'Back', cocktails_path, class:"btn btn-primary"%>
<%= link_to 'Edit', edit_cocktail_path(@cocktail), class:"btn btn-primary" %>
<%= link_to 'Delete_all', cocktail_path(@cocktail), method: :delete, class:"btn btn-danger" %>

app/views/doses/new.html.erb
<h1>Add new dose to <%=  @cocktail.name %></h1>
  <div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 ">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.association :ingredient  %>
        <%= f.input :description %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

<!-- collection: ingrediant.all also works -->
s

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>